CREATE DATABASE SENAI_HROADS;
GO

USE SENAI_HROADS;
GO

CREATE TABLE CLASSE
(
	idClasse INT PRIMARY KEY IDENTITY ,
	TipoClasse VARCHAR(200) NOT NULL
);
GO

CREATE TABLE TIPO_HABILIDADE
(
	idTipoHab INT PRIMARY KEY IDENTITY ,
	TipoHab VARCHAR (200) NOT NULL
);
GO

CREATE TABLE HABILIDADE
(
	idHabilidade INT PRIMARY KEY IDENTITY ,
	idTipoHab INT FOREIGN KEY REFERENCES TIPO_HABILIDADE (idTipoHab),
	Nome VARCHAR (200) NOT NULL 
);
GO

CREATE TABLE CLASSE_HABILIDADE
(
	idClasse INT FOREIGN KEY REFERENCES CLASSE(idClasse),
	idHabilidade INT FOREIGN KEY REFERENCES HABILIDADE (idHabilidade)

);
GO

CREATE TABLE PERSONAGEM
(
	idPersonagem INT PRIMARY KEy IDENTITY,
	idClasse INT FOREIGN  KEY REFERENCES Classe(idClasse),
	NomePer VARCHAR (200) NOT NULL,
	CapaMaxVida INT NOT NULL,
	CapaMaxMana INT NOT NULL,
	DataAtual DATE NOT NULL,
	DataCriacao DATE NOT NULL
);
GO

CREATE TABLE TIPO_USUARIO 
(
	idTipoUsuario INT PRIMARY KEY IDENTITY,
	permissao VARCHAR(200) NOT NULL
);
GO

CREATE TABLE USUARIO
(
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario INT FOREIGN KEY REFERENCES TIPO_USUARIO(idTipoUsuario),
	email VARCHAR(200) NOT NULL,
	senha VARCHAR(100) NOT NULL
	
);
GO